const express = require('express');
const serverless = require('serverless-http');
const app = express();
const router = express.Router();

// Mock Data
const customerData = [
    {
        accountNo: '1021',
        companyName: 'AAT Training Hub',
        authorizedEmail: 'john.smith1@gmail.com',
        phone: '91111021',
        plan: 'Cloud Telephony Basic',
        phoneExtensionCount: 3,
        chatExtensionCount: 0,
        totalSub: 45,
        addon: 0,
        professionalFee: 0,
        total: 45,
        startDate: '2026-01-05',
        endDate: '2026-12-31',
        status: 'Active',
        friendlyStatus: 'Your account with AAT Training Hub is Active.',
    },
    {
        accountNo: '1022',
        companyName: 'Absolute Corporate',
        authorizedEmail: 'emma.johnson2@gmail.com',
        phone: '91111022',
        plan: 'Cloud Telephony Basic',
        phoneExtensionCount: 2,
        chatExtensionCount: 0,
        totalSub: 30,
        addon: 0,
        professionalFee: 0,
        total: 30,
        startDate: '2026-01-15',
        endDate: '2026-06-14',
        status: 'Active',
        friendlyStatus: "Absolute Corporate's account is currently Active.",
    },
    {
        accountNo: '1023',
        companyName: 'Accord Law Chambers',
        authorizedEmail: 'michael.brown3@gmail.com',
        phone: '91111023',
        plan: 'Cloud Telephony Basic',
        phoneExtensionCount: 10,
        chatExtensionCount: 0,
        totalSub: 150,
        addon: 0,
        professionalFee: 0,
        total: 150,
        startDate: '2026-02-01',
        endDate: '2027-01-31',
        status: 'Active',
        friendlyStatus: 'Accord Law Chambers is Active.',
    },
    {
        accountNo: '1024',
        companyName: 'Act Point Salon',
        authorizedEmail: 'olivia.davis4@gmail.com',
        phone: '91111024',
        plan: 'Nautilus Talk Basic',
        phoneExtensionCount: 5,
        chatExtensionCount: 0,
        totalSub: 75,
        addon: 0,
        professionalFee: 0,
        total: 75,
        startDate: '2026-02-10',
        endDate: '2026-08-09',
        status: 'Active',
        friendlyStatus: 'Act Point Salon account is Active.',
    },
    {
        accountNo: '1025',
        companyName: 'Adept Health',
        authorizedEmail: 'william.miller5@gmail.com',
        phone: '91111025',
        plan: 'Nautilus Talk Enterprise / Nautilus Chat',
        phoneExtensionCount: 8,
        chatExtensionCount: 8,
        totalSub: 920,
        addon: 0,
        professionalFee: 800,
        total: 1720,
        startDate: '2026-03-01',
        endDate: '2026-12-31',
        status: 'Pending',
        friendlyStatus: 'Adept Health account is currently Pending setup.',
    },
    {
        accountNo: '1026',
        companyName: 'Advantage Medical Group',
        authorizedEmail: 'sophia.wilson6@gmail.com',
        phone: '91111026',
        plan: 'Nautilus Talk Basic',
        phoneExtensionCount: 5,
        chatExtensionCount: 0,
        totalSub: 75,
        addon: 0,
        professionalFee: 0,
        total: 75,
        startDate: '2026-03-15',
        endDate: '2026-09-14',
        status: 'Active',
        friendlyStatus: 'Advantage Medical Group is Active.',
    },
    {
        accountNo: '1027',
        companyName: 'Afeli Insurance Brokers',
        authorizedEmail: 'james.moore7@gmail.com',
        phone: '91111027',
        plan: 'Contact Center Enterprise',
        phoneExtensionCount: 6,
        chatExtensionCount: 0,
        totalSub: 600,
        addon: 0,
        professionalFee: 0,
        total: 600,
        startDate: '2026-04-01',
        endDate: '2026-10-31',
        status: 'Active',
        friendlyStatus: 'Afeli Insurance Brokers is Active.',
    },
    {
        accountNo: '1028',
        companyName: 'Alaska / Decor Singapore',
        authorizedEmail: 'isabella.taylor8@gmail.com',
        phone: '91111028',
        plan: 'Cloud Telephony Basic',
        phoneExtensionCount: 1,
        chatExtensionCount: 0,
        totalSub: 15,
        addon: 0,
        professionalFee: 0,
        total: 15,
        startDate: '2026-04-20',
        endDate: '2027-04-19',
        status: 'Active',
        friendlyStatus: 'Alaska / Decor Singapore is Active.',
    },
    {
        accountNo: '1029',
        companyName: 'Animal Arts',
        authorizedEmail: 'benjamin.anderson9@gmail.com',
        phone: '91111029',
        plan: 'Cloud Telephony Basic',
        phoneExtensionCount: 2,
        chatExtensionCount: 0,
        totalSub: 30,
        addon: 0,
        professionalFee: 0,
        total: 30,
        startDate: '2026-05-01',
        endDate: '2026-11-30',
        status: 'Active',
        friendlyStatus: 'Animal Arts is Active.',
    },
    {
        accountNo: '1030',
        companyName: 'Arc',
        authorizedEmail: 'mia.thomas10@gmail.com',
        phone: '91111030',
        plan: 'Cloud Telephony Basic',
        phoneExtensionCount: 1,
        chatExtensionCount: 0,
        totalSub: 15,
        addon: 0,
        professionalFee: 0,
        total: 15,
        startDate: '2026-05-18',
        endDate: '2026-08-17',
        status: 'Active',
        friendlyStatus: 'Arc account is Active.',
    },
    {
        accountNo: '1031',
        companyName: 'Ascendo Academy',
        authorizedEmail: 'alexander.jackson11@gmail.com',
        phone: '91111031',
        plan: 'Cloud Telephony Basic',
        phoneExtensionCount: 1,
        chatExtensionCount: 0,
        totalSub: 15,
        addon: 0,
        professionalFee: 0,
        total: 15,
        startDate: '2026-06-01',
        endDate: '2027-05-31',
        status: 'Active',
        friendlyStatus: 'Ascendo Academy is Active.',
    },
    {
        accountNo: '1032',
        companyName: 'At-Sunrice',
        authorizedEmail: 'charlotte.white12@gmail.com',
        phone: '91111032',
        plan: 'Cloud Telephony Basic',
        phoneExtensionCount: 4,
        chatExtensionCount: 0,
        totalSub: 60,
        addon: 0,
        professionalFee: 0,
        total: 60,
        startDate: '2026-06-25',
        endDate: '2026-12-24',
        status: 'Active',
        friendlyStatus: 'At-Sunrice is Active.',
    },
    {
        accountNo: '1033',
        companyName: 'ATOMAXR',
        authorizedEmail: 'daniel.harris13@gmail.com',
        phone: '91111033',
        plan: 'Cloud Telephony Basic',
        phoneExtensionCount: 4,
        chatExtensionCount: 0,
        totalSub: 60,
        addon: 0,
        professionalFee: 0,
        total: 60,
        startDate: '2026-07-01',
        endDate: '2027-06-30',
        status: 'Active',
        friendlyStatus: 'ATOMAXR is Active.',
    },
    {
        accountNo: '1034',
        companyName: 'Audio House',
        authorizedEmail: 'amelia.martin14@gmail.com',
        phone: '91111034',
        plan: 'Contact Center Enterprise / Nautilus Chat',
        phoneExtensionCount: 10,
        chatExtensionCount: 10,
        totalSub: 1150,
        addon: 0,
        professionalFee: 800,
        total: 1950,
        startDate: '2026-07-15',
        endDate: '2026-10-14',
        status: 'Active',
        friendlyStatus: 'Audio House is Active.',
    },
    {
        accountNo: '1035',
        companyName: 'Autism Step',
        authorizedEmail: 'matthew.thompson15@gmail.com',
        phone: '91111035',
        plan: 'Contact Center Enterprise',
        phoneExtensionCount: 2,
        chatExtensionCount: 0,
        totalSub: 200,
        addon: 0,
        professionalFee: 500,
        total: 700,
        startDate: '2026-08-01',
        endDate: '2027-01-31',
        status: 'Overdue',
        friendlyStatus: 'Autism Step has an Overdue balance.',
    },
    {
        accountNo: '1036',
        companyName: 'Best Home',
        authorizedEmail: 'harper.garcia16@gmail.com',
        phone: '91111036',
        plan: 'Contact Center Enterprise',
        phoneExtensionCount: 2,
        chatExtensionCount: 0,
        totalSub: 200,
        addon: 0,
        professionalFee: 500,
        total: 700,
        startDate: '2026-08-20',
        endDate: '2027-08-19',
        status: 'Active',
        friendlyStatus: 'Best Home is Active.',
    },
    {
        accountNo: '1037',
        companyName: "Brinda's",
        authorizedEmail: 'david.martinez17@gmail.com',
        phone: '91111037',
        plan: 'Contact Center Enterprise',
        phoneExtensionCount: 2,
        chatExtensionCount: 0,
        totalSub: 200,
        addon: 0,
        professionalFee: 500,
        total: 700,
        startDate: '2026-09-01',
        endDate: '2026-12-31',
        status: 'Active',
        friendlyStatus: "Brinda's account is Active.",
    },
    {
        accountNo: '1038',
        companyName: 'Busy Bees',
        authorizedEmail: 'evelyn.robinson18@gmail.com',
        phone: '91111038',
        plan: 'Contact Center Enterprise',
        phoneExtensionCount: 5,
        chatExtensionCount: 0,
        totalSub: 500,
        addon: 0,
        professionalFee: 0,
        total: 500,
        startDate: '2026-09-10',
        endDate: '2027-03-09',
        status: 'Active',
        friendlyStatus: 'Busy Bees is Active.',
    },
    {
        accountNo: '1039',
        companyName: 'CBRE',
        authorizedEmail: 'joseph.clark19@gmail.com',
        phone: '91111039',
        plan: 'Nautilus Talk Enterprise',
        phoneExtensionCount: 3,
        chatExtensionCount: 0,
        totalSub: 300,
        addon: 0,
        professionalFee: 0,
        total: 300,
        startDate: '2026-10-01',
        endDate: '2027-09-30',
        status: 'Active',
        friendlyStatus: 'CBRE is Active.',
    },
    {
        accountNo: '1040',
        companyName: 'LHN',
        authorizedEmail: 'abigail.rodriguez20@gmail.com',
        phone: '91111040',
        plan: 'Nautilus Talk Enterprise',
        phoneExtensionCount: 6,
        chatExtensionCount: 0,
        totalSub: 600,
        addon: 0,
        professionalFee: 0,
        total: 600,
        startDate: '2026-10-25',
        endDate: '2027-04-24',
        status: 'Active',
        friendlyStatus: 'LHN account is Active.',
    },
];

router.get('/customer-list/:query', (req, res) => {
    const query = req.params.query.toLowerCase();

    // Multi-field search logic
    const customer = customerData.find(
        (c) =>
            c.accountNo.toLowerCase() === query ||
            c.phone.toLowerCase() === query ||
            c.companyName.toLowerCase() === query ||
            c.authorizedEmail.toLowerCase() === query,
    );

    if (customer) {
        res.json({ status: 'success', data: customer });
    } else {
        // Crucial: return 404 to stop the Zendesk AI from hallucinating
        res.status(404).json({
            status: 'error',
            message: 'Customer not found',
        });
    }
});

// Optional: Route to see all for your own testing
router.get('/customer-list', (req, res) => {
    res.json({ status: 'success', data: customerData });
});

app.use('/api/', router); // This handles the redirected path
app.use('/.netlify/functions/api/', router); // This handles the direct path

module.exports.handler = serverless(app);
