const express = require('express');
const serverless = require('serverless-http');
const app = express();
const router = express.Router();

// Mock Data
const customerData = [
    {
        accountNo: '1021',
        companyName: 'AAT Training Hub',
        authorizedEmail: 'john.smith1@gmail.com',
        phone: '91111021',
        totalSub: 45,
        addon: 0,
        professionalFee: 0,
        total: 45,
        billingAddress: 'Blk 123 Ang Mo Kio Ave 6 #05-123',
        status: 'Active',
        friendlyStatus: 'Your account with AAT Training Hub is Active.',
    },
    {
        accountNo: '1022',
        companyName: 'Absolute Corporate',
        authorizedEmail: 'emma.johnson2@gmail.com',
        phone: '91111022',
        totalSub: 30,
        addon: 0,
        professionalFee: 0,
        total: 30,
        billingAddress: 'Blk 456 Bedok North St 3 #12-456',
        status: 'Active',
        friendlyStatus: "Absolute Corporate's account is currently Active.",
    },
    {
        accountNo: '1023',
        companyName: 'Accord Law Chambers',
        authorizedEmail: 'michael.brown3@gmail.com',
        phone: '91111023',
        totalSub: 150,
        addon: 0,
        professionalFee: 0,
        total: 150,
        billingAddress: 'Blk 789 Tampines Ave 4 #08-210',
        status: 'Active',
        friendlyStatus: 'Accord Law Chambers is Active.',
    },
    {
        accountNo: '1024',
        companyName: 'Act Point Salon',
        authorizedEmail: 'olivia.davis4@gmail.com',
        phone: '91111024',
        totalSub: 75,
        addon: 0,
        professionalFee: 0,
        total: 75,
        billingAddress: 'Blk 321 Jurong East St 31 #10-654',
        status: 'Active',
        friendlyStatus: 'Act Point Salon account is Active.',
    },
    {
        accountNo: '1025',
        companyName: 'Adept Health',
        authorizedEmail: 'william.miller5@gmail.com',
        phone: '91111025',
        totalSub: 920,
        addon: 0,
        professionalFee: 800,
        total: 1720,
        billingAddress: 'Blk 654 Hougang Ave 8 #03-198',
        status: 'Pending',
        friendlyStatus: 'Adept Health account is currently Pending setup.',
    },
    {
        accountNo: '1026',
        companyName: 'Advantage Medical Group',
        authorizedEmail: 'sophia.wilson6@gmail.com',
        phone: '91111026',
        totalSub: 75,
        addon: 0,
        professionalFee: 0,
        total: 75,
        billingAddress: 'Blk 987 Woodlands Ave 5 #09-321',
        status: 'Active',
        friendlyStatus: 'Advantage Medical Group is Active.',
    },
    {
        accountNo: '1027',
        companyName: 'Afeli Insurance Brokers',
        authorizedEmail: 'james.moore7@gmail.com',
        phone: '91111027',
        totalSub: 600,
        addon: 0,
        professionalFee: 0,
        total: 600,
        billingAddress: 'Blk 159 Yishun St 11 #11-456',
        status: 'Active',
        friendlyStatus: 'Afeli Insurance Brokers is Active.',
    },
    {
        accountNo: '1028',
        companyName: 'Alaska / Decor Singapore',
        authorizedEmail: 'isabella.taylor8@gmail.com',
        phone: '91111028',
        totalSub: 15,
        addon: 0,
        professionalFee: 0,
        total: 15,
        billingAddress: 'Blk 753 Clementi Ave 2 #06-789',
        status: 'Active',
        friendlyStatus: 'Alaska / Decor Singapore is Active.',
    },
    {
        accountNo: '1029',
        companyName: 'Animal Arts',
        authorizedEmail: 'benjamin.anderson9@gmail.com',
        phone: '911111029',
        totalSub: 30,
        addon: 0,
        professionalFee: 0,
        total: 30,
        billingAddress: 'Blk 852 Sengkang East Way #14-852',
        status: 'Active',
        friendlyStatus: 'Animal Arts is Active.',
    },
    {
        accountNo: '1030',
        companyName: 'Arc',
        authorizedEmail: 'mia.thomas10@gmail.com',
        phone: '91111030',
        totalSub: 15,
        addon: 0,
        professionalFee: 0,
        total: 15,
        billingAddress: 'Blk 963 Punggol Dr #07-963',
        status: 'Active',
        friendlyStatus: 'Arc account is Active.',
    },
    {
        accountNo: '1031',
        companyName: 'Ascendo Academy',
        authorizedEmail: 'alexander.jackson11@gmail.com',
        phone: '91111031',
        totalSub: 15,
        addon: 0,
        professionalFee: 0,
        total: 15,
        billingAddress: 'Blk 741 Bukit Batok West Ave 8 #05-741',
        status: 'Active',
        friendlyStatus: 'Ascendo Academy is Active.',
    },
    {
        accountNo: '1032',
        companyName: 'At-Sunrice',
        authorizedEmail: 'charlotte.white12@gmail.com',
        phone: '91111032',
        totalSub: 60,
        addon: 0,
        professionalFee: 0,
        total: 60,
        billingAddress: 'Blk 258 Toa Payoh East #10-258',
        status: 'Active',
        friendlyStatus: 'At-Sunrice is Active.',
    },
    {
        accountNo: '1033',
        companyName: 'ATOMAXR',
        authorizedEmail: 'daniel.harris13@gmail.com',
        phone: '91111033',
        totalSub: 60,
        addon: 0,
        professionalFee: 0,
        total: 60,
        billingAddress: 'Blk 369 Queenstown Ave #13-369',
        status: 'Active',
        friendlyStatus: 'ATOMAXR is Active.',
    },
    {
        accountNo: '1034',
        companyName: 'Audio House',
        authorizedEmail: 'amelia.martin14@gmail.com',
        phone: '91111034',
        totalSub: 1150,
        addon: 0,
        professionalFee: 800,
        total: 1950,
        billingAddress: 'Blk 147 Bishan St 11 #04-147',
        status: 'Active',
        friendlyStatus: 'Audio House is Active.',
    },
    {
        accountNo: '1035',
        companyName: 'Autism Step',
        authorizedEmail: 'matthew.thompson15@gmail.com',
        phone: '91111035',
        totalSub: 200,
        addon: 0,
        professionalFee: 500,
        total: 700,
        billingAddress: 'Blk 753 Choa Chu Kang North 5 #08-753',
        status: 'Overdue',
        friendlyStatus: 'Autism Step has an Overdue balance.',
    },
    {
        accountNo: '1036',
        companyName: 'Best Home',
        authorizedEmail: 'harper.garcia16@gmail.com',
        phone: '91111036',
        totalSub: 200,
        addon: 0,
        professionalFee: 500,
        total: 700,
        billingAddress: 'Blk 951 Serangoon Ave 2 #15-951',
        status: 'Active',
        friendlyStatus: 'Best Home is Active.',
    },
    {
        accountNo: '1037',
        companyName: "Brinda's",
        authorizedEmail: 'david.martinez17@gmail.com',
        phone: '91111037',
        totalSub: 200,
        addon: 0,
        professionalFee: 500,
        total: 700,
        billingAddress: 'Blk 357 Pasir Ris St 31 #06-357',
        status: 'Active',
        friendlyStatus: "Brinda's account is Active.",
    },
    {
        accountNo: '1038',
        companyName: 'Busy Bees',
        authorizedEmail: 'evelyn.robinson18@gmail.com',
        phone: '91111038',
        totalSub: 500,
        addon: 0,
        professionalFee: 0,
        total: 500,
        billingAddress: 'Blk 852 Jurong West St 81 #09-852',
        status: 'Active',
        friendlyStatus: 'Busy Bees is Active.',
    },
    {
        accountNo: '1039',
        companyName: 'CBRE',
        authorizedEmail: 'joseph.clark19@gmail.com',
        phone: '91111039',
        totalSub: 300,
        addon: 0,
        professionalFee: 0,
        total: 300,
        billingAddress: 'Blk 468 Admiralty Dr #11-468',
        status: 'Active',
        friendlyStatus: 'CBRE is Active.',
    },
    {
        accountNo: '1040',
        companyName: 'LHN',
        authorizedEmail: 'abigail.rodriguez20@gmail.com',
        phone: '91111040',
        totalSub: 600,
        addon: 0,
        professionalFee: 0,
        total: 600,
        billingAddress: 'Blk 246 Compassvale Rd #12-246',
        status: 'Active',
        friendlyStatus: 'LHN account is Active.',
    },
];

router.get('/customer-list/:query', (req, res) => {
    const query = req.params.query.toLowerCase();

    // Multi-field search logic
    const customer = customerData.find(
        (c) =>
            c.accountNo.toLowerCase() === query ||
            c.phone.toLowerCase() === query ||
            c.companyName.toLowerCase() === query ||
            c.authorizedEmail.toLowerCase() === query,
    );

    if (customer) {
        res.json({ status: 'success', data: customer });
    } else {
        // Crucial: return 404 to stop the Zendesk AI from hallucinating
        res.status(404).json({
            status: 'error',
            message: 'Customer not found',
        });
    }
});

// Optional: Route to see all for your own testing
router.get('/customer-list', (req, res) => {
    res.json({ status: 'success', data: customerData });
});

app.use('/api/', router); // This handles the redirected path
app.use('/.netlify/functions/api/', router); // This handles the direct path

module.exports.handler = serverless(app);
